document.documentElement.className = document.documentElement.className.replace('no-js', '');

window.theme = {
strings: {
    addToCart: "Add to Cart",
    addForFree: "Add for Free",
    soldOut: "Sold Out",
    unavailable: "Unavailable",
    save: "Save",
    off: "Off",
    quickshop: "QUICKSHOP",
    customize: "Customize",
    shopNow: "Shop Now",
    cart: "My Cart",
    freeShippingLabel: "\u003cp\u003e\u003cstrong\u003eFree shipping\u003c\/strong\u003e for orders over €110\u003c\/p\u003e",
    freeProductLabel: "",
    promoLabel: "",
    checkout: "proceed to checkout",
    qty: "QTY",
    fullCart: "\u003ca href=\"\/cart\"\u003eSee full cart\u003c\/a\u003e to enter discount codes",
    subtotal: "Subtotal",
    total: "Total",
    remove: "Remove",
    quantity: "QTY",
    cartEmpty: "Your cart is currently empty.",
    readMore: "Read more",
    readLess: "Read less",
    new: "New",
    preorder: "PRE-ORDER",
    backorder: "BACKORDER",
    notify: "Notify Me",
    free: "Free",
    totalDiscount: "You\u0026#39;re saving"
},
moneyFormat: "€{{amount_with_comma_separator}}",
freeShippingPrice: 11000,
freeShippingPriceMin: 7000,
freeProduct:  null ,
freeProductPrice: 12000,
abios: "https:\/\/api-prod.g2esports.com\/series",
abiosToken: "1c980701-7d3e-4d0a-978e-ba6cf602e0f3",
klaviyoAPI: "TD9WXN",
klaviyoListID: "UskBLC",
apiUrl: "https:\/\/api.ipstack.com\/check?access_key=cbc80eded2ab368b296031873e4397ee",
cartRebuy: "\u003cdiv data-rebuy-id=\"18236\"\u003e\u003c\/div\u003e"
};